---
name: CI
"on":
  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron: "30 4 * * 1"

defaults:
  run:
<<<<<<< Updated upstream
    working-directory: "chadek.api_automation_toolbox"
=======
    working-directory: "hello_asso_sync"
>>>>>>> Stashed changes

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v4
        with:
<<<<<<< Updated upstream
          path: "chadek.api_automation_toolbox"
=======
          path: "hello_asso_sync"
>>>>>>> Stashed changes

      - name: Set up Python 3.
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install test dependencies.
        run: pip3 install pylint ovh requests

      - name: Lint code.
        run: |
          pylint *.py

  # test:
  #   name: Test
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Check out the codebase.
  #       uses: actions/checkout@v4
  #       with:
  #         path: "chadek.api_automation_toolbox"

  #     - name: Set up Python 3.
  #       uses: actions/setup-python@v5
  #       with:
  #         python-version: "3.x"

  #     - name: Install test dependencies.
  #       run: pip3 install ovh request

  #     - name: Run Python tests.
  #       run: python3 helloasso_dump.py --conf hello-asso-automation-conf.json

